use String.format("%tF") instead of "%tY-%tm-%td" to avoid java.util.MissingFormatArgumentException: Format specifier '%tm' errors
As to why java suddenly started complaining about java.util.MissingFormatArgumentException: Format specifier '%tm' errors I have no idea but the fact is that it did on the 1st of may 2020:

```
Failed to download Podcast from https://example.com/1.mp3
java.util.MissingFormatArgumentException: Format specifier '%tm'
```

Given that the intention of this format string is to produce an ISO date (YYYY-MM-DD) and given that String.format has a special formatter for this which does _not_ produce this error it seems logical to use it.